add systemd-compatible logging
gkrizek/ghi pull request #10
Opened 2021-02-24 15:53 UTC by Kvaciral

Because systemd's own logging system is more conventional and convenient than using `&>> /some/where/ghi.log` I've added the means to do so in a seperate module (also for refactoring of logging config in index.py en server.py).

2021-02-24 16:21 UTC, laanwj commented
I use this setup and it works great for me!

2021-02-24 16:22 UTC, laanwj commented on examples/ghi.service.md
> +ExecStart=/bin/bash -c "PYTHONPATH="/home/ubuntu/ghi/ghi:$PYTHONPATH" python3 /home/ubuntu/ghi/ghi/server.py --port 8080 --systemd
FWIW, i didn't have to set the `PYTHONPATH=…` here, it automatically picks that up from the current directory.

2021-02-24 16:24 UTC, laanwj commented on examples/ghi.service.md
>  _You might need to create the log file first because the user might not have permissions to /var/log_
"In that case you might need to …"  (could be part of last paragraph)

2021-02-25 03:09 UTC, gkrizek requested changes
Thanks for the PR! This is great.

There's one small comment about the main handler to make sure it's still compatible with AWS Lambda.

2021-02-25 03:09 UTC, gkrizek commented on ghi/index.py
> +def handler(event, sysd, context=None):
```suggestion
def handler(event, context=None, sysd=None):
```

This needs to have `context` first because that's how AWS Lambda invokes the function. We also need to set `sysd` to None so it can still work in Lambda. This should keep it functional on both Lambda and on a server.

2021-02-25 12:38 UTC, Kvaciral commented on ghi/index.py
> +def handler(event, sysd, context=None):
Done! I wasn't able to test GHI with AWS Lambda..

2021-02-25 16:12 UTC, laanwj commented on ghi/index.py
> +def handler(event, sysd, context=None):
Oops,I also didn't know the handler signature was hardcoded.

2021-02-25 16:50 UTC, gkrizek approved these changes
Looks good! Thanks for the PR!

2021-02-25 16:50 UTC, merged